# Generated by Django 2.0.7 on 2018-07-11 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Temperature', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Humidity', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
